### ISSUE TITLE
Remove 2016 User Conference pages

### ISSUE THREAD

**Issue by evpaassen** [eveoh/website-mytimetable#29]
Also remove the link in the footer.

**Comment by marcokrikke** [comment]
Ik voel meer iets voor een archiefje itt compleet weggooien.

**Comment by evpaassen** [comment]
Er staat nu een echt niks op die pagina. Een lijst met delegates en het programma, maar meer eigenlijk niet. Het lijkt me in ieder geval niet dat die delegates tot in de eeuwigheid op die pagina willen blijven staan.

**Comment by evpaassen** [comment]
Overal staat ook nog *Video available soon*, lekker schraal weer.

**Comment by marcokrikke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zu4e6bEa&#x2F;844-conference-pagina-website"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Conference pagina website</a>

**Comment by marcokrikke** [comment]
Archief geïntroduceerd. Pagina's opgeschoond.
